# =================================================
# BASE CONFIGURATION (Default)
# =================================================
server:
  port: 18080
  netty:
    connection-timeout: 2s
    idle-timeout: 30s
# --- Spring Boot Active Profile ---
spring:
  profiles:
    active: local
  aes:
    key: hmmcbui123456789

  # --- R2DBC (Production Placeholder) ---
  r2dbc:
    # 운영 DB 정보는 CI/CD 파이프라인에서 환경 변수로 주입
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    # TODO: Connection Pooling 추후 올릴 예정
    pool:
      enabled: true
      initial-size: 20
      max-size: 100
      validation-query: SELECT 1 FROM DUAL
logging:
  level:
    root: WARN
    com.hmm.backend: INFO
springwolf:
  docket:
    base-package: com.hmm.cbui.global.websocket.handler
    info:
      title: WebSocket Chat API
      version: 1.0.0
      description: 채팅 메시지를 위한 WebSocket API 문서
    servers:
      default:
        protocol: ws
        url: ws://localhost:18080/ws


