-- 반드시 PDB(FREEPDB1) 컨텍스트로 전환
ALTER SESSION SET CONTAINER = FREEPDB1;

WHENEVER SQLERROR EXIT SQL.SQLCODE

DECLARE
v_cnt NUMBER(1);
BEGIN
SELECT COUNT(*) INTO v_cnt FROM dba_users WHERE username = 'CBUI_WAS';

IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[CREATE USER CBUI_WAS IDENTIFIED BY "hmm1234**" -- Local Only
      DEFAULT TABLESPACE users
      QUOTA UNLIMITED ON users]';
ELSE
    EXECUTE IMMEDIATE q'[ALTER USER CBUI_WAS ACCOUNT UNLOCK]';
EXECUTE IMMEDIATE q'[ALTER USER CBUI_WAS IDENTIFIED BY "hmm1234**"]';
END IF;

  -- 권한은 여러 번 실행돼도 무해
EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO CBUI_WAS';
EXECUTE IMMEDIATE 'GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE JOB TO CBUI_WAS';
END;
/